package dev.atvremote.protocol

/**
 * Minimal JSON reader for loading test vectors.
 *
 * Deliberately dependency-free: the vectors file is generated by our own
 * tooling and contains only objects, arrays, strings, numbers and literals.
 */
object MiniJson {

    fun parse(text: String): Any? {
        val p = Parser(text)
        val v = p.value()
        p.skipWhitespace()
        require(p.pos >= text.length) { "trailing JSON at ${p.pos}" }
        return v
    }

    private class Parser(val s: String) {
        var pos = 0

        fun skipWhitespace() {
            while (pos < s.length && s[pos].isWhitespace()) pos++
        }

        fun value(): Any? {
            skipWhitespace()
            return when (val c = s[pos]) {
                '{' -> obj()
                '[' -> arr()
                '"' -> str()
                't' -> literal("true", true)
                'f' -> literal("false", false)
                'n' -> literal("null", null)
                else -> if (c == '-' || c.isDigit()) num()
                else throw IllegalArgumentException("Unexpected '$c' at $pos")
            }
        }

        fun <T> literal(text: String, value: T): T {
            require(s.startsWith(text, pos)) { "bad literal at $pos" }
            pos += text.length
            return value
        }

        fun obj(): Map<String, Any?> {
            val out = LinkedHashMap<String, Any?>()
            pos++ // consume {
            skipWhitespace()
            if (s[pos] == '}') {
                pos++
                return out
            }
            while (true) {
                skipWhitespace()
                val key = str()
                skipWhitespace()
                require(s[pos] == ':') { "expected ':' at $pos" }
                pos++
                out[key] = value()
                skipWhitespace()
                when (s[pos]) {
                    ',' -> pos++
                    '}' -> {
                        pos++
                        return out
                    }
                    else -> throw IllegalArgumentException("expected ',' or '}' at $pos")
                }
            }
        }

        fun arr(): List<Any?> {
            val out = mutableListOf<Any?>()
            pos++ // consume [
            skipWhitespace()
            if (s[pos] == ']') {
                pos++
                return out
            }
            while (true) {
                out.add(value())
                skipWhitespace()
                when (s[pos]) {
                    ',' -> pos++
                    ']' -> {
                        pos++
                        return out
                    }
                    else -> throw IllegalArgumentException("expected ',' or ']' at $pos")
                }
            }
        }

        fun str(): String {
            require(s[pos] == '"') { "expected string at $pos" }
            pos++
            val sb = StringBuilder()
            while (s[pos] != '"') {
                if (s[pos] == '\\') {
                    pos++
                    when (val e = s[pos]) {
                        'n' -> sb.append('\n')
                        't' -> sb.append('\t')
                        'r' -> sb.append('\r')
                        'b' -> sb.append('\b')
                        'f' -> sb.append('\u000C')
                        'u' -> {
                            sb.append(s.substring(pos + 1, pos + 5).toInt(16).toChar())
                            pos += 4
                        }
                        else -> sb.append(e)
                    }
                } else {
                    sb.append(s[pos])
                }
                pos++
            }
            pos++
            return sb.toString()
        }

        fun num(): Any {
            val start = pos
            if (s[pos] == '-') pos++
            while (pos < s.length && (s[pos].isDigit() || s[pos] in ".eE+-")) pos++
            val text = s.substring(start, pos)
            return if (text.any { it in ".eE" }) text.toDouble() else text.toLong()
        }
    }
}
